server: main.cpp ./pool/thread_pool.h ./http/http_conn.cpp ./http/http_conn.h ./itc/itc.h ./timer/sort_timer_list.cpp ./timer/sort_timer_list.h
	g++ -W -Wall -o ../build/server main.cpp ./pool/thread_pool.h ./http/http_conn.cpp ./http/http_conn.h ./itc/itc.h ./timer/sort_timer_list.cpp ./timer/sort_timer_list.h -lpthread


clean:
	rm  -r server